[2021-01-25 18:02:15,322] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.load_data 2021-01-25T18:02:10.449183+00:00 [queued]>
[2021-01-25 18:02:15,381] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.load_data 2021-01-25T18:02:10.449183+00:00 [queued]>
[2021-01-25 18:02:15,382] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 18:02:15,382] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-01-25 18:02:15,383] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 18:02:15,444] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): load_data> on 2021-01-25T18:02:10.449183+00:00
[2021-01-25 18:02:15,448] {standard_task_runner.py:54} INFO - Started process 52848 to run task
[2021-01-25 18:02:15,480] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'load_data', '2021-01-25T18:02:10.449183+00:00', '--job_id', '51', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmps_9sxwv_']
[2021-01-25 18:02:15,484] {standard_task_runner.py:78} INFO - Job 51: Subtask load_data
[2021-01-25 18:02:15,551] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.load_data 2021-01-25T18:02:10.449183+00:00 [running]> 3f8da9634a9c
[2021-01-25 18:02:15,635] {logging_mixin.py:112} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py:2612: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,
[2021-01-25 18:02:15,985] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-01-25 18:02:16,000] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=load_data, execution_date=20210125T180210, start_date=20210125T180215, end_date=20210125T180216
[2021-01-25 18:02:20,296] {local_task_job.py:102} INFO - Task exited with return code 0
