[2021-01-25 21:20:13,592] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.load_data 2021-01-25T21:20:07.801920+00:00 [queued]>
[2021-01-25 21:20:13,624] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.load_data 2021-01-25T21:20:07.801920+00:00 [queued]>
[2021-01-25 21:20:13,625] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 21:20:13,626] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-01-25 21:20:13,626] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-25 21:20:13,674] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): load_data> on 2021-01-25T21:20:07.801920+00:00
[2021-01-25 21:20:13,678] {standard_task_runner.py:54} INFO - Started process 58782 to run task
[2021-01-25 21:20:13,703] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'load_data', '2021-01-25T21:20:07.801920+00:00', '--job_id', '56', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmpu906uump']
[2021-01-25 21:20:13,707] {standard_task_runner.py:78} INFO - Job 56: Subtask load_data
[2021-01-25 21:20:13,794] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.load_data 2021-01-25T21:20:07.801920+00:00 [running]> 3f8da9634a9c
[2021-01-25 21:20:13,861] {logging_mixin.py:112} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py:2612: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,
[2021-01-25 21:20:14,233] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-01-25 21:20:14,255] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=load_data, execution_date=20210125T212007, start_date=20210125T212013, end_date=20210125T212014
[2021-01-25 21:20:18,553] {local_task_job.py:102} INFO - Task exited with return code 0
